/* Theme preferences */
function applyTheme(theme){document.documentElement.dataset.theme=theme;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==='dark'?'#1e1e2e':'#fff8fc';try{localStorage.setItem('chess-theme',theme)}catch(e){}}
function applyUiTheme(theme){document.documentElement.dataset.uiTheme=theme;try{localStorage.setItem('chess-ui-theme',theme)}catch(e){}}
function applyBoardTheme(theme){document.documentElement.dataset.boardTheme=theme;try{localStorage.setItem('chess-board-theme',theme)}catch(e){}}
let savedTheme='light',savedUi='sakura',savedBoard='classic';try{savedTheme=localStorage.getItem('chess-theme')||'light';savedUi=localStorage.getItem('chess-ui-theme')||'sakura';savedBoard=localStorage.getItem('chess-board-theme')||'classic'}catch(e){}applyTheme(savedTheme==='dark'?'dark':'light');applyUiTheme(savedUi);applyBoardTheme(savedBoard);
document.getElementById('themeSettings').onclick=()=>document.getElementById('themeModal').classList.add('open');document.getElementById('uiThemeSelect').value=savedUi;document.getElementById('boardThemeSelect').value=savedBoard;document.getElementById('uiThemeSelect').onchange=e=>applyUiTheme(e.target.value);document.getElementById('boardThemeSelect').onchange=e=>applyBoardTheme(e.target.value);document.getElementById('themeLight').onclick=()=>applyTheme('light');document.getElementById('themeDark').onclick=()=>applyTheme('dark');document.getElementById('closeThemeSettings').onclick=()=>document.getElementById('themeModal').classList.remove('open');document.getElementById('themeModal').onclick=e=>{if(e.target.id==='themeModal')e.currentTarget.classList.remove('open')};document.getElementById('clearLog').onclick=()=>{document.getElementById('log').textContent='';log('log cleared')};
document.getElementById('startTraining').type='button';document.getElementById('playMatch').type='button';document.getElementById('simulateMove').type='button';document.getElementById('newGame').type='button';document.getElementById('flip').type='button';document.getElementById('stopTrain').type='button';document.getElementById('startTraining').onclick=()=>{trainBatch().catch(e=>{log('training launch error: '+e.message);setStatus('error','training failed to start',0)})};document.getElementById('playMatch').onclick=()=>{playMatch().catch(e=>{busy=false;log('Play error: '+e.message);setStatus('error',e.message,0);renderAll()})};document.getElementById('simulateMove').onclick=()=>{simulateOneMove().catch(e=>{busy=false;log('1 move error: '+e.message);setStatus('error',e.message,0);renderAll()})};document.getElementById('newGame').onclick=()=>newGame();document.getElementById('flip').onclick=()=>{flipped=!flipped;renderBoard()};document.getElementById('stopTrain').onclick=()=>{cancelEngine();training=false;busy=false;setStatus('paused','stopped');renderAll();toast('stopped')};document.getElementById('matchType').onchange=()=>{const type=document.getElementById('matchType').value;document.getElementById('engineField').style.display=type==='learner-engine'?'grid':'none';updateMatchBadge();setStatus('ready','press Play to randomize sides and start the match',0)};
document.getElementById('engineSelect').onchange=async()=>{selectedEngine=document.getElementById('engineSelect').value;document.getElementById('customEngineField').style.display=selectedEngine==='custom-wasm'?'grid':'none';matchEpoch++;await createStockfish(true);updateMatchBadge();setStatus('ready',engineDisplayLabel()+' selected · press Play',0)};
document.getElementById('customEngineUrl').onchange=async()=>{if(selectedEngine==='custom-wasm'){matchEpoch++;await createStockfish(true);}};document.getElementById('saveBrain').onclick=()=>saveBrain();document.getElementById('loadBrain').onclick=loadBrain;document.getElementById('resetBrain').onclick=resetBrain;document.getElementById('exportBrain').onclick=exportBrain;document.getElementById('importBrain').onclick=importBrain;document.getElementById('promoModal').onclick=e=>{if(e.target.id==='promoModal')e.currentTarget.classList.remove('open')};

// Bootstrap in layers: the board is rendered first; persistence and Stockfish are allowed to fail independently.
brain=new TinyNet(Date.now());
resetRepetition();
try{updateMatchBadge()}catch(e){console.error(e)}
try{renderPlayers();renderAll()}catch(e){console.error('initial render failed',e);const el=document.getElementById('log');if(el)el.textContent+='initial render failed: '+e.message+'\\n';}
try{log('Chess Learning Lab '+CONFIG.version+' initialized')}catch(e){}
try{log('learner uses only chess rules from the environment; strategy starts random and is learned from experience')}catch(e){}
loadBrain().catch(e=>log('brain load error: '+e.message));
try{createStockfish()}catch(e){log('Stockfish startup error: '+e.message);setEngineUi('engine unavailable',false)}
