/* Move review + reward feedback */
function estimateEloFromReview(accuracy,result=0){const a=Math.max(0,Math.min(100,Number(accuracy)||0));const outcome=Number(result)||0;return Math.round(Math.max(400,Math.min(2000,450+a*10.5+outcome*100)));}
function updateEstimatedElo(accuracy,result=0){estimatedElo=estimateEloFromReview(accuracy,result);return estimatedElo;}
function expectedPoints(cp){const x=Math.max(-1200,Math.min(1200,cp))/180;return 1/(1+Math.exp(-x))}

function pieceValue(t){return ({p:1,n:3,b:3,r:5,q:9,k:0})[t]||0}

function materialScore(c,color){let n=0;for(const row of c.board())for(const p of row)if(p&&p.color===color)n+=pieceValue(p.type);return n}

function classifyMove(beforeCp,afterCp,bestUci,rec,bestAfterCp,bestMove,bestAfterFen){const moverWhite=rec.side==='w';const before=moverWhite?beforeCp:-beforeCp,after=moverWhite?afterCp:-afterCp;const bestAfter=moverWhite?bestAfterCp:-bestAfterCp;const loss=Math.max(0,expectedPoints(before)-expectedPoints(after));const bestGain=expectedPoints(bestAfter)-expectedPoints(before);const isBest=bestUci===rec.uci;const delta=after-before;let quality;if(isBest&&Math.abs(delta)<8)quality='Best';else if(!isBest&&bestGain>=0.12&&loss<0.20)quality='Miss';else if(loss<0.02)quality='Excellent';else if(loss<0.05)quality='Good';else if(loss<0.10)quality='Inaccuracy';else if(loss<0.20)quality='Mistake';else quality='Blunder';let brilliant=false,great=false;if(isBest&&bestMove&&bestAfterFen){const recFen=typeof rec.fen==='string'?rec.fen:(rec.fen&&typeof rec.fen.fen==='function'?rec.fen.fen():null);if(recFen){const beforeBoard=new Chess(recFen),afterBest=new Chess(bestAfterFen);const ownBefore=materialScore(beforeBoard,rec.side),ownAfter=materialScore(afterBest,rec.side);const sacrificed=ownAfter<ownBefore;const stillPlayable=bestAfter>-100;if(sacrificed&&stillPlayable&&before<250){brilliant=true;quality='Brilliant'}}}if(!brilliant&&isBest&&bestGain>=0.12&&before<250){great=true;quality='Great'}return {quality,loss,isBest,bestGain,brilliant,great};}

async function finishGameReview(epoch=matchEpoch){if(reviewRunning||lastReviewedEpoch===epoch||!moveRecords.length||epoch!==matchEpoch)return;lastReviewedEpoch=epoch;reviewRunning=true;reviewState={running:true,text:'checking each move against the engine…'};renderReview();if(!stockfishReady){reviewRunning=false;reviewState={running:false,accuracy:'—',text:'Stockfish was not ready, so this game could not be reviewed yet.',counts:{}};renderReview();log('game review skipped: Stockfish not ready');return}const counts={Brilliant:0,Great:0,Best:0,Excellent:0,Good:0,Inaccuracy:0,Mistake:0,Blunder:0,Miss:0};let totalLoss=0,reviewed=0;for(let i=0;i<moveRecords.length;i++){if(epoch!==matchEpoch)break;const rec=moveRecords[i];const recFen=typeof rec.fen==='string'?rec.fen:(rec.fen&&typeof rec.fen.fen==='function'?rec.fen.fen():null);if(!recFen)continue;const before=await stockfishAnalyze(recFen,7);const c=new Chess(recFen);const mv=c.move({from:rec.uci.slice(0,2),to:rec.uci.slice(2,4),promotion:rec.uci[4]});if(!mv||!before)continue;const after=await stockfishAnalyze(c.fen(),7);if(!after)continue;let bestAfterCp=after.score,bestMove=null,bestAfterFen=null;if(before.best){const bc=new Chess(recFen);const bm=bc.move({from:before.best.slice(0,2),to:before.best.slice(2,4),promotion:before.best[4]});if(bm){bestMove=bm;bestAfterFen=bc.fen();const ba=await stockfishAnalyze(bestAfterFen,7);if(ba)bestAfterCp=ba.score}}const cls=classifyMove(before.score,after.score,before.best,rec,bestAfterCp,bestMove,bestAfterFen);rec.quality=cls.quality;rec.pointDelta=({Brilliant:12,Great:9,Best:6,Excellent:3,Good:1,Inaccuracy:0,Mistake:-5,Blunder:-10,Miss:-7}[cls.quality]??0);if(isCheckmate(c))rec.pointDelta+=20;if(mv.promotion)rec.pointDelta+=3;counts[cls.quality]++;totalLoss+=cls.loss;reviewed++;if((i&3)===3){reviewState.text='reviewing move '+(i+1)+' / '+moveRecords.length;renderReview();}}const accuracy=Math.max(0,Math.min(100,Math.round(100*(1-(totalLoss/Math.max(1,reviewed))))));const learnerWinner=(isCheckmate(game)&&((game.turn()==='w'&&botBlack==='learner')||(game.turn()==='b'&&botWhite==='learner'))) ? 1 : 0; const learnerLoser=(isCheckmate(game)&&((game.turn()==='w'&&botWhite==='learner')||(game.turn()==='b'&&botBlack==='learner'))) ? -1 : 0; const elo=updateEstimatedElo(accuracy,learnerWinner||learnerLoser); reviewState={running:false,accuracy,text:'engine feedback has been recorded for the learner. Estimated Elo: '+elo+'. This is a rough local estimate, not an official rating.',counts};reviewRunning=false;renderMoves();renderReview();log('game review complete · '+accuracy+'% · '+reviewed+' moves classified');feedReviewToLearner();}

function feedReviewToLearner(){if(!brain)return;const weights={Brilliant:12,Great:9,Best:6,Excellent:3,Good:1,Inaccuracy:0,Mistake:-5,Blunder:-10,Miss:-7};let delta=0,signal=0,n=0;for(const r of moveRecords){if(!r.quality||r.actor!=='learner')continue;const p=r.pointDelta??(weights[r.quality]??0);delta+=p;signal+=p/12;n++;}if(isCheckmate(game)){const winner=game.turn()==='w'?'black':'white';const learnerSide=(botWhite==='learner'&&winner==='white')||(botBlack==='learner'&&winner==='black');if(learnerSide)delta+=20;else if(botWhite==='learner'||botBlack==='learner')delta-=20;}if(repetitionDetections)delta-=2*repetitionDetections;if(drawReason(game)&&!repetitionDetections)delta+=2;points+=delta;brain.reviewSignal=(brain.reviewSignal||0)*.9+signal/Math.max(1,n);brain.rewardHistory=(brain.rewardHistory||[]).concat([{points:delta,accuracy:reviewState?.accuracy??0,generation}]).slice(-200);steps+=n;evalRecord=(brain.reviewSignal).toFixed(2);renderStats();saveBrain(false);log('learner received move-quality feedback · '+(delta>=0?'+':'')+delta+' points · signal '+brain.reviewSignal.toFixed(2));}